name: PRODUCTION Deployment
on: 
  push:
    branches:
      - master

jobs:
  production-tsmediacms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - run: npm install yarn -g
      - run: yarn install
      - run: yarn build

      - name: refresh repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          port: ${{ secrets.PROD_PORT }}
          username: ${{ secrets.PROD_SSH_USER }}
          key: ${{ secrets.PROD_PRIV_KEY }}
          script: ${{ secrets.REFRESH_CODE_PROD }}

      - name: Deploy to PROD server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_PRIV_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "./*"
          REMOTE_HOST: ${{ secrets.PROD_HOST }}
          REMOTE_PORT: ${{ secrets.PROD_PORT }}
          REMOTE_USER: ${{ secrets.PROD_SSH_USER }}
          TARGET: ${{ secrets.PROD_DIR_TARGET }}

      - name: update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_SSH_USER }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_PRIV_KEY }}
          script: |
            chown -R www-data:www-data ${{ secrets.PROD_DIR_TARGET }}
            cd ${{ secrets.PROD_DIR_TARGET }} && pm2 restart tsmedia-cms
